server:
  log_level: info
  http_listen_address: 0.0.0.0:12345

metrics:
  global:
    scrape_interval: 60s

  configs: []

logs:
  configs:
    - name: app-logs
      positions:
        filename: /tmp/positions.yaml
      clients:
        - url: http://loki:3100/loki/api/v1/push
      scrape_configs:
        - job_name: app-logs
          static_configs:
            - targets:
                - localhost
              labels:
                job: app-logs
                app: movierama
                environment: production
                __path__: /app/logs/*.log