auth_enabled: false

server:
  http_listen_port: 3100

common:
  path: /loki
  storage:
    filesystem:
      directory: /loki/chunks
  replication_factor: 1

schema_config:
  configs:
    - from: 2020-10-15
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem

  filesystem:
    directory: /loki/chunks