scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'movierama-app'
    metrics_path: 'movierama/api/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']