server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchsize: 1000

scrape_configs:
  - job_name: docker
    static_configs:
      - targets: [ 'localhost' ]
        labels:
          job: springboot
          __path__: /app/logs/*.log